In [4]:
!pip install numpy

In [8]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\selva\anaconda3\lib\site-packages (1.17.0)


In [9]:
#simple numpy
import numpy as np

aone =np.array([1,2,3,4,5,6])
aone


array([1, 2, 3, 4, 5, 6])

In [12]:
#Assign value to variable
import numpy as np
num = [1,2,3,4,5]
aone =np.array(num)
aone

array([1, 2, 3, 4, 5])

In [17]:
#Array of zeros
import numpy as np
array_of_zero = np.zeros((3,5))
array_of_zero


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])