In [1]:
#identity matrix
#get 1 as diagnal value
import numpy as np

arr_eye = np.eye(3)
arr_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
#we mentioned row, column, datatype
import numpy as np

arr_eye = np.eye(3,4,dtype=int)
arr_eye

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [4]:
#builtin functions
#arange
import numpy as np

arr_eye = np.arange(2,20,2)
arr_eye

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
#arange in float
import numpy as np

arr_eye = np.arange(2,3,0.2)
arr_eye

array([2. , 2.2, 2.4, 2.6, 2.8])

In [12]:
#2d array
import numpy as np
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
#2d array verification
import numpy as np
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d.shape

(2, 3)

In [13]:
#multi dimensional
import numpy as np
arrnd = np.arange(6).reshape(3,2)
arrnd

array([[0, 1],
       [2, 3],
       [4, 5]])