In [14]:
#numpy arithmetic operation
import numpy as np
a = np.array([10,10,10,10])
b = np.array([5,5,5,5])
#Addition
c= a+b
print("Addition:")
print(c)
#subtraction
d = a-b
print("Subtraction:")
print(d)
#multiplications
e = a*b
print("multiplications:")
print(e)
#divisons
f = a/b
print("divisons:")
print(f)
#modulo divisons
g = a%b
print("modulo divisons:")
print(g)
#power
h = a**3
print("power:")
print(h)

Addition:
[15 15 15 15]
Subtraction:
[5 5 5 5]
multiplications:
[50 50 50 50]
divisons:
[2. 2. 2. 2.]
modulo divisons:
[0 0 0 0]
power:
[1000 1000 1000 1000]
