In [12]:
#numpy indexing and slicing
import numpy as np
a= np.arange(11)**2
print(a)
print(a[2])
print(a[-2])
print(a[2:])
print(a[2:-2])
print(a[:7])
print(a[:11:2])
#-ve indexing used 
print(a[::-1])
a="selva"
print(len(a))
print(a[::-1])

[  0   1   4   9  16  25  36  49  64  81 100]
4
81
[  4   9  16  25  36  49  64  81 100]
[ 4  9 16 25 36 49 64]
[ 0  1  4  9 16 25 36]
[  0   4  16  36  64 100]
[100  81  64  49  36  25  16   9   4   1   0]
5
avles
