In [4]:
#convert list as a numpy array
import numpy as np
lst = [1,2,3,4]
c = np.array(lst)
c
#print(c)

array([1, 2, 3, 4])

In [5]:
#2d array
d = np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [8]:
#3d array
e =np.array([[1,2,3],[4,5,6],[7,8,9]])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#shape and data type checking
f = np.array([[1,2],[3,4]])
print(f.shape)
print(f.dtype)


(2, 2)
int32


In [14]:
#shape and data type checking
g = np.array([[1.0,2.0],[3.0,4.0]])
print(g.shape)
print(g.dtype)


(2, 2)
float64


In [16]:
#zeros and ones
h = np.zeros([2,2])
print(h)

[[0. 0.]
 [0. 0.]]


In [18]:
#zeros and ones
i = np.zeros([3,3],dtype= 'int')
print(i)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [19]:
#ones
j = np.ones([3,3],dtype= 'int')
print(j)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [22]:
#return empty array
k = np.empty([2,2])
print(k)

[[0 0]
 [0 0]]


In [23]:
#return empty array
l = np.empty([2,2],dtype='int')
print(l)

[[1206015968        456]
 [         0          0]]


In [24]:
#return empty array
m = np.empty([2,2],dtype='float')
print(m)

[[9.68211513e-312 4.82412339e+228]
 [7.03540903e+199 1.27734658e-152]]


In [25]:
#identity matrix
#only value one is diagnal positions and remaining zeros
n = np.eye(5,5)
print(n)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [34]:
#reshape
o = np.array([[1,2,3],[4,5,6]])
print(o)
print("\nafter reshape:")
p =o.reshape(3,2)
print(p)
#flaten
print("\n FLatten:")
q = p.flatten()
print(q)


[[1 2 3]
 [4 5 6]]

after reshape:
[[1 2]
 [3 4]
 [5 6]]

 FLatten:
[1 2 3 4 5 6]


In [42]:
#arange
#it is look like python range. we will generate values dynamically. we need to specify only start position and end position and increasing steps.
r = np.arange(12)
print(r)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [2]:
import numpy as np
s=np.arange(12).reshape(3,4)
print(s)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
