In [1]:
#Numpy Iterating:
#example:
import numpy as np
a=np.arange(12)**2
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0


In [3]:
#Iterating in arrays
students = np.array([['selva','gana','pati'],[99,98,97],[100,98,98]])
for i in students:
    print(i)

['selva' 'gana' 'pati']
['99' '98' '97']
['100' '98' '98']


In [4]:
#Flatten[Using to fetching values in one by one.row wise,coloumn wise]
#row
students = np.array([['selva','gana','pati'],[99,98,97],[100,98,98]])
for i in students.flatten():
    print(i)

selva
gana
pati
99
98
97
100
98
98


In [5]:
#FLatten Column wise
students = np.array([['selva','gana','pati'],[99,98,97],[100,98,98]])
for i in students.flatten(order = 'f'):
    print(i)

selva
99
100
gana
98
98
pati
97
98


In [10]:
#ndtier[Similer to the flatten but ndtier gave best background cpu utilization]
#nditer row wise
import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
for i in np.nditer(a):
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [12]:
#nditer coloumn wise
import numpy as np
a=np.arange(12).reshape(3,4)
print(a)
for i in np.nditer(a,order = 'F'):
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
4
8
1
5
9
2
6
10
3
7
11
